### ISSUE TITLE
Could the example CSS also be part of the package (in NPM etc.)

### ISSUE THREAD

**Issue by OwenEdwards** [WICG/focus-visible#141]
I'm using the current version of focus-visible in a [demo together with the video.js framework](https://github.com/OwenEdwards/video.js/tree/experimental/use-focus-visible-package). I [reference the focus-visible.js script](https://github.com/WICG/focus-visible#1-add-the-script-to-your-page) from my HTML, but I need to add the [example CSS](https://github.com/WICG/focus-visible#2-update-your-css) from README.md manually:

````css
/*
  This will hide the focus indicator if the element receives focus via the mouse,
  but it will still show up on keyboard focus.
*/
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}
````

Could this be added to the repo as a `focus-visible.css` file, and then added to the package, so that it can be used in multiple places? Or is it not part of the core of the polyfil? In that case, could it be placed in the `demo` folder? Just seems like it would be helpful to have it as part of the bundle.
