### ISSUE TITLE
Having an issue with Firefox and this polyfill

### ISSUE THREAD

**Issue by ayumihamsaki** [WICG/focus-visible#201]
Hi,

I have set up how Rob suggests and my Google Chrome is working fine with the polyfill.

With Firefox, they suggest to use something different: `-moz-focusring` instead of `:focus`

Setting the following code for the ` :focus-visible`

I have the following:

```css
-moz-focusring:not(.focus-ring) {
	outline: none;
}
```

This works fine and hides the focus ring. But the ` :focus-visible` with the polyfill doesn't work and display the focus ring when I press tab now.

Got a feeling the polyfill needs updating to ref the firefox [-moz-focusring](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring)

p.s. a small codepen demoing the firefox css pseudo-class: https://codepen.io/patrickhlauke/pen/WvzGag

**Comment by anpos231** [comment]
This polyfill enables a class called '.focus-visible', not a pseudo-selector ':focus-visible'.
So instead of using `.something:focus-visible` you should use `.something.focus-visible`

**Comment by ayumihamsaki** [comment]
I see, I have that bit wrong.

Also your '`readme`' file is missing some information

It says the following:

# Backwards compatibility
Until all browsers ship `:focus-visible` developers will need to use it defensively to avoid accidentally
removing focus styles in legacy browsers. This is easy to do with the polyfill.

```css
/*
  This will hide the focus indicator if the element receives focus via the mouse,
  but it will still show up on keyboard focus.
*/
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}

/*
  Optionally: Define a strong focus indicator for keyboard focus.
  If you choose to skip this step then the browser's default focus
  indicator will be displayed instead.
*/
.js-focus-visible .focus-visible {
  …
}
```

But I think it should be updated to this:

# Backwards compatibility
Until all browsers ship `:focus-visible` developers will need to use it defensively to avoid accidentally
removing focus styles in legacy browsers. This is easy to do with the polyfill.

```css
/*
  Firefox uses their own :-moz-focusring CSS pseudo-class, a Mozilla extension that is similar to the :focus pseudo-class
*/
.js-focus-visible -moz-focusring:not(.focus-visible) {
  outline: none;
}
/*
  The rest of the browsers used the :focus pseudo-class
*/
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}

/*
  Optionally: Define a strong focus indicator for keyboard focus.
  If you choose to skip this step then the browser's default focus
  indicator will be displayed instead.
*/
.js-focus-visible .focus-visible {
  …
}
```

**Comment by ayumihamsaki** [comment]
I see, I have that bit wrong.

Also your '`readme`' file is missing some information

It says the following:

# Backwards compatibility
Until all browsers ship `:focus-visible` developers will need to use it defensively to avoid accidentally
removing focus styles in legacy browsers. This is easy to do with the polyfill.

```css
/*
  This will hide the focus indicator if the element receives focus via the mouse,
  but it will still show up on keyboard focus.
*/
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}

/*
  Optionally: Define a strong focus indicator for keyboard focus.
  If you choose to skip this step then the browser's default focus
  indicator will be displayed instead.
*/
.js-focus-visible .focus-visible {
  …
}
```

But I think it should be updated to this:

# Backwards compatibility
Until all browsers ship `:focus-visible` developers will need to use it defensively to avoid accidentally
removing focus styles in legacy browsers. This is easy to do with the polyfill.

```css
/*
  Firefox uses their own :-moz-focusring CSS pseudo-class, a Mozilla extension that is similar to the :focus pseudo-class
*/
.js-focus-visible :-moz-focusring:not(.focus-visible) {
  outline: none;
}

/*
  The rest of the browsers used the :focus pseudo-class
*/
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}

/*
  Optionally: Define a strong focus indicator for keyboard focus.
  If you choose to skip this step then the browser's default focus
  indicator will be displayed instead.
*/
.js-focus-visible .focus-visible {
  …
}
```
