### ISSUE TITLE
CSS outline not removed on NextJS

### ISSUE THREAD

**Issue by aquaductape** [WICG/focus-visible#233]
On NextJS, a React Server Side Render framework, the focus outline still appears when clicking on button elements. I've used this library successfully in client React frameworks such as create-react-app.

focus-visible is loaded by `_app.js` page
```
import "focus-visible";

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />;
}

export default MyApp;
```
Tried loading focus-visible inside `_document.js` page, didn't make a difference.

The css used by both demos.
```css
// removes outline when clicking
.js-focus-visible :focus:not(.focus-visible) {
  outline: none;
}

button {
  display: block;
  cursor: pointer;
  border: none;
  background: #ccc;
  margin: 10px 0;
}

// displays when focusing with keyboard
button.focus-visible {
  color: red;
  outline: 1px solid red;
}
```
[Demo: focus-visible removes outline on create-react-app upon clicking](https://codesandbox.io/s/github/aquaductape/cra-focus-visible)

![Screenshot from 2020-06-22 21-47-37](https://user-images.githubusercontent.com/29286430/85361935-12d06300-b4d2-11ea-9bc5-31d7f192acd8.png)

[Demo: focus-visible fails to remove outline on NextJS upon clicking](https://codesandbox.io/s/github/aquaductape/next-focus-visible)

![Screenshot from 2020-06-22 21-46-28](https://user-images.githubusercontent.com/29286430/85361895-f6ccc180-b4d1-11ea-9b64-8bbbe545c19e.png)
